name: Check updated files

on:
  pull_request:
    branches:
      - main

jobs:
  check-updated-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v39
        with:
          files: mag/* gds/* verilog/rtl/*

      - name: Run step if any file(s) in the mag, gds or verilog/rtl folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the mag, gds or verilog/rtl folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          exit 1
