name: Check updated files

on:
  pull_request:
    branches:
      - main

jobs:
  check-updated-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check updated files
        id: check-updated-files
        run: |
          git diff --name-only HEAD HEAD~
          | grep -E '(mag|gds|verilog/rtl)/'
          if [[ $? -eq 0 ]]; then
            exit 1
          fi
